from logging import (
    CRITICAL,
    ERROR,
    WARNING,
    INFO,
    FATAL,
    DEBUG,
    NOTSET,
)

NOTSET_COLOR = "#808080"
DEBUG_COLOR = "#00FFFF"
INFO_COLOR = "#00C400"
WARNING_COLOR = "#FFE240"
ERROR_COLOR = "#FF0000"
CRITICAL_COLOR = "#700000"
FATAL_COLOR = CRITICAL_COLOR

COLORS = {
    NOTSET: NOTSET_COLOR,
    DEBUG: DEBUG_COLOR,
    INFO: INFO_COLOR,
    WARNING: WARNING_COLOR,
    ERROR: ERROR_COLOR,
    FATAL: FATAL_COLOR,
    CRITICAL: CRITICAL_COLOR,
}
